// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDArbSi3gH0WV70FtF5B38fOEGLXykr3-U',
    appId: '1:66643620149:web:4eff6485bec44e7d4e5c7c',
    messagingSenderId: '66643620149',
    projectId: 'student-management-info-mobapp',
    authDomain: 'student-management-info-mobapp.firebaseapp.com',
    storageBucket: 'student-management-info-mobapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe4iXPSQ_MGf_p0Yg1lhqlE0KNSqp1hYE',
    appId: '1:66643620149:android:0a941c570dcb38ba4e5c7c',
    messagingSenderId: '66643620149',
    projectId: 'student-management-info-mobapp',
    storageBucket: 'student-management-info-mobapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNMspldaqw8gtSFmo5RG_qWu6m-292bcg',
    appId: '1:66643620149:ios:74c3d44e53b6e6964e5c7c',
    messagingSenderId: '66643620149',
    projectId: 'student-management-info-mobapp',
    storageBucket: 'student-management-info-mobapp.firebasestorage.app',
    iosBundleId: 'com.example.trueStudentmgntMobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNMspldaqw8gtSFmo5RG_qWu6m-292bcg',
    appId: '1:66643620149:ios:74c3d44e53b6e6964e5c7c',
    messagingSenderId: '66643620149',
    projectId: 'student-management-info-mobapp',
    storageBucket: 'student-management-info-mobapp.firebasestorage.app',
    iosBundleId: 'com.example.trueStudentmgntMobapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDArbSi3gH0WV70FtF5B38fOEGLXykr3-U',
    appId: '1:66643620149:web:2f673d96437954754e5c7c',
    messagingSenderId: '66643620149',
    projectId: 'student-management-info-mobapp',
    authDomain: 'student-management-info-mobapp.firebaseapp.com',
    storageBucket: 'student-management-info-mobapp.firebasestorage.app',
  );

}